### ISSUE TITLE
Current Air Temp set to 0°c - Ravelli Stove

### ISSUE THREAD

**Issue by GauthierCrp** [vincentwolsink/home_assistant_micronova_agua_iot#11]
Hello everyone,

I installed recently the integration for a **_Ravelli Chiara S stove._**

The plugin works well, for most part, I can Run, Start, select the Fan Level of the stove. 
But I'm not able to display or retrieve the **Current Air Temp**. In the Ravelli app, on mobile, the temperature from the remote sensor, and the smoke temperature are displayed. But I don't know hom to display it, in the climate entity.

![image](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/30144651/01a70f0e-672c-4941-8aac-038dda9547f6)

The current air temp is coming from this remote controller :

![image](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/30144651/132841c1-26d7-4a85-8e8c-f64496240cc4)

Could you please, help me, this temperature is quiet important to set automation avec automate the stove through HA

Many Thanks in advance

**Comment by vincentwolsink** [comment]
Hi! Please install [v0.1.4-beta1](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/releases/tag/v0.1.4-beta1). Enable debug logging for aguaiot in Home Assistant, reload the integration and send me the debug output.

I will then check if the temperature from the remote is in some other register than expected.

**Comment by jipem01** [comment]
Hello Gauthier,Could you privide details/models of your stove.In register map, we could find temperatures related to canalizations (canalization_1_temp_get).But we could also find temp_air_get and temp_air_palm_get.As temp_air_get always return 0 it should be something between canalizarion or palm temp.I fear that we will end by adding a dictionnary to handle each brand (models?) specificity...
-------- Message d'origine --------De : GauthierCrp ***@***.***> Date : 27/07/2023  15:01  (GMT+01:00) À : vincentwolsink/home_assistant_micronova_agua_iot ***@***.***> Cc : Subscribed ***@***.***> Objet : Re: [vincentwolsink/home_assistant_micronova_agua_iot] Current Air Temp set to 0°c - Ravelli Stove (Issue #11) 
Hi !  Excuse me for not responding ! It's very hot in France these days and I almost forgot that I have a Stove at home :)
I updated the integration to the 0.1.4 and active Debug Mode.
Here is the log file after enabling the debug mode and restart the intégration :
home-assistant_2023-07-27T12-53-31.841Z.log
I hope it is telling you something, because for me, it's like alien language...
Thank you very much for your help !!

**Comment by vincentwolsink** [comment]
Hi @GauthierCrp, which temperature did your stove display when creating this error log?
Or can you create a new one and tell us the temperature your stove/controller is displaying.

**Comment by GauthierCrp** [comment]
Hello,

I'm back with configuring this stove !

By comparing to an other temperature sensor next to the remote controller. I think, that the current air temperature is in the field : 

![image](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/30144651/22ddcbc9-197d-4e50-a5bf-ba0e82ca8f2a)

The current temperature in the living room is 21°C

Here is the diagnostic file : 

[config_entry-aguaiot-bd0ed33603d660c90cbf85dd6e6a8ee8.json.txt](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/files/12701635/config_entry-aguaiot-bd0ed33603d660c90cbf85dd6e6a8ee8.json.txt)

Could you add it the the pluggin in order to retrieve the correct temperature in HA ?
Is there something I can make to help you ?

Many thanks  !
Best Regards

**Comment by vincentwolsink** [comment]
Hi, try [v0.2.0-beta6](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/releases/tag/v0.2.0-beta6) :)

**Comment by GauthierCrp** [comment]
Thank you very much!
Do you know, how to push a beta version in HA ?
I don't find the config to change the channel !

Thanks!
Best regards

**Comment by vincentwolsink** [comment]
See the [HACS FAQ](https://hacs.xyz/docs/faq/beta/)

**Comment by GauthierCrp** [comment]
Thanks you very much Vincent ! It's working !

![image](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/30144651/9e3f4505-525d-4a07-ad88-4f0f651fc8e5)

Best Regards
