### ISSUE TITLE
Set clock time

### ISSUE THREAD

**Issue by inode-** [vincentwolsink/home_assistant_micronova_agua_iot#116]
Hello,

it would very useful to be able also to set the clock time of them. The stove doesn't have a mechanism to syncronize the clock automatically, but it's an operation that can be done in the app.

It would be useful to me to be able to automatize this operation via HA.

Thank you

**Comment by vincentwolsink** [comment]
Hi @inode-,

Yes also my stove clock drifts quite a lot. 😄
Since Home Assistant doesn't seem to support a UI for doing date/time entries, what I can do is add a service to the integration to change time/date on the stove. I can also add a generic "sync clock" service that will sync the stove time/date to the Home Assistant one. Which you can then automatically call every night or so, to keep the stove clock in sync.

**Comment by inode-** [comment]
Sync clock service will be lovable!

**Comment by vincentwolsink** [comment]
This change implied a bit more changes than anticipated. But I got there.

I added a service `aguaiot.sync_clock`. Make sure to target it to the **main** climate entity for your stove (so not to an extra fan or canalization entity).

**Comment by vincentwolsink** [comment]
Let me know if it works for you @inode- 🙂

**Comment by thibaud-sanchez** [comment]
Can you help me to use it or add something in the doc ?
I would like to auto sync every night at 3, so it will support day night saving automatically and prevent shifting
