### ISSUE TITLE
Problem with integration since 0.3.1

### ISSUE THREAD

**Issue by rassha** [vincentwolsink/home_assistant_micronova_agua_iot#163]
Hi,

I didn't use integration since last winter (march this year, or so..) Everything worked OK then...
I saw that integration was updated to 0.4.9 but in my case, it wont work as it should be...

For example, it shows that heat is always ON (status "HEAT"), but it isn't (Stove is OFF mode) 
Temperature readings are fine, but status is wrong.... So, I can't turn stove ON or OFF

I rolled back to 0.31 (and tried almost every version till latest beta 0.5.1) and it works now as it should be.

Stove is AlfaPlam Commo 21, Customer_code: 862148, rocognized as "ALFA_IDRO"

Here are diagnostic log attached, may be helpful
[config_entry-aguaiot-01J9NCE0NAW56ZJYH58B79QMYH.json](https://github.com/user-attachments/files/17291453/config_entry-aguaiot-01J9NCE0NAW56ZJYH58B79QMYH.json)

**Comment by vincentwolsink** [comment]
I am matching pellet stove status on the translation labels provided by the vendor api. Because the numerical states differ in meaning across different vendors. Unfortunately it seems AlfaPlam made a translation error where the English label for "OFF" is actually "START". That is why the integration thinks the stove is on. I am not sure how to fix this yet without impacting others. Let me think about it.

**Comment by rassha** [comment]
Great work Vinsent..It works now

Thanks for quick fix.
I hope that it will work in all future updates...
